mod commands;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .invoke_handler(tauri::generate_handler![
            commands::get_app_config,
            commands::set_app_config,
            commands::read_target_config,
            commands::list_apps,
            commands::delete_app,
            commands::get_active_app,
            commands::set_active_app,
            commands::list_runs,
            commands::read_evidence,
            commands::read_text_file,
            commands::list_flows,
            commands::list_devices,
            commands::read_device_aliases,
            commands::set_target_serial,
            commands::set_target_scope,
            commands::upsert_device_alias,
            commands::delete_device_alias,
            commands::export_device_aliases,
            commands::import_device_aliases,
            commands::list_resource_files,
            commands::upload_resource_file,
            commands::delete_resource_file,
            commands::list_text_resources,
            commands::upsert_text_resource,
            commands::delete_text_resource,
            commands::read_summary,
            commands::read_structure,
            commands::save_run_record,
            commands::list_run_records,
            commands::read_run_record,
            commands::delete_run_record,
            commands::run_flow,
            commands::run_flow_repair,
            commands::abort_run,
            commands::new_run,
            commands::sync_sheets,
            commands::judge_result,
            commands::register_issue,
            commands::doc_report,
            commands::check_claude_cli,
            commands::probe_apk,
            commands::install_apk,
            commands::register_app,
            commands::list_apk_versions,
            commands::save_apk_version,
            commands::scan_cleanup,
            commands::move_to_trash,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
